### ISSUE TITLE
Is this amd64-specific?

### ISSUE THREAD

**Issue by chmeeedalf** [FreeBSDDesktop/kms-firmware#1]
Is the KMS firmware really amd64 specific?  The base (FreeBSD src) drm2 also targets powerpc64, and at least radeon cards work in powerpc64.

https://github.com/FreeBSDDesktop/kms-firmware/blob/e94f3aef43f53dce7eea90fcd20a4405b841fed7/Makefile#L6

**Comment by iotamudelta** [comment]
Probably not. It is however only tested as a companion to the LinuxKPI DRM/KMS bits which are only available on amd64. If you are willing to test on i386 and powerpc64, I am certainly happy to relax the architecture check here and in the port.

**Comment by chmeeedalf** [comment]
linuxkpi builds fine for powerpc64, and is built by default as a module for all architectures.  I don't have a i386 machine to test with, only various powerpc and powerpc64 machines.  I see no reason to restrict to amd64 only if it compiles, and for now I think it's sufficient to only restrict at the port level, while leaving the actual target open to any.

**Comment by iotamudelta** [comment]
My statement was not about base lkpi, it's about the lkpi bits in the graphics/drm-next-kmod port (and the DRM/KMS code in there) - those haven't been tested to my knowledge on anything but amd64. But I am happy to pull a change here.

I actually believe it'd be worthwhile - if it works - also for i386/powerpc64 users since, in difference to base, I am keeping the firmwares pretty up to date here.

**Comment by chmeeedalf** [comment]
Ah, okay, I misunderstood.  I can generate a pull request this weekend if you don't make the change first.

**Comment by zeising** [comment]
The firmware port is now buildable on all FreeBSD architectures, however, the drivers in drm*kmod aren't. Since this is for the firmware, can this be closed, and an issue for the actual drivers be opened?

**Comment by chmeeedalf** [comment]
Sure. I'll open a new issue when I get to a real computer.
